# Generated by Django 3.2.18 on 2023-06-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20230606_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('id_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
