# Generated by Django 3.2.19 on 2023-06-12 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('-date',)},
        ),
    ]
