# Generated by Django 3.2.19 on 2023-06-13 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(choices=[('小兒科', '小兒科'), ('婦產科', '婦產科'), ('外科', '外科'), ('內科', '內科')], default='小兒科', max_length=10),
        ),
    ]
